# Generated by Django 5.2.16 on 2026-09-22 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_algorithm_average_case_complexity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('readability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('simplicity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True, max_length=5000)),
                ('weaknesses', models.TextField(blank=True, max_length=5000)),
                ('use_cases', models.TextField(blank=True, max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implementation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.algorithmimplementation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('performance__isnull', True), ('performance__range', (1, 5)), _connector='OR'), name='review_performance_1_to_5'), models.CheckConstraint(condition=models.Q(('readability__isnull', True), ('readability__range', (1, 5)), _connector='OR'), name='review_readability_1_to_5'), models.CheckConstraint(condition=models.Q(('simplicity__isnull', True), ('simplicity__range', (1, 5)), _connector='OR'), name='review_simplicity_1_to_5'), models.CheckConstraint(condition=models.Q(('reliability__isnull', True), ('reliability__range', (1, 5)), _connector='OR'), name='review_reliability_1_to_5'), models.CheckConstraint(condition=models.Q(('learning_value__isnull', True), ('learning_value__range', (1, 5)), _connector='OR'), name='review_learning_value_1_to_5'), models.CheckConstraint(condition=models.Q(('overall__isnull', True), ('overall__range', (1, 5)), _connector='OR'), name='review_overall_1_to_5')],
            },
        ),
    ]
