# Generated by Django 5.2.16 on 2026-07-18 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='core.problem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=20)),
                ('source_type', models.CharField(choices=[('built_in', 'Built-in'), ('custom', 'Custom')], default='built_in', max_length=20)),
                ('registry_key', models.CharField(blank=True, help_text='Το μοναδικό key που θα συνδέει την εγγραφή με built-in Python implementation.', max_length=150, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_reference', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='core.algorithm')),
            ],
            options={
                'ordering': ['algorithm__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('algorithm', 'slug'), name='unique_implementation_slug_per_algorithm')],
            },
        ),
        migrations.AddConstraint(
            model_name='algorithm',
            constraint=models.UniqueConstraint(fields=('problem', 'slug'), name='unique_algorithm_slug_per_problem'),
        ),
    ]
