# Generated by Django 5.2.16 on 2026-07-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='average_case_complexity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='best_case_complexity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='worst_case_complexity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
